#!/bin/bash

partitions=$(tmsh list auth partition | awk '/^auth/ {print $3}')

echo -e "Discovering offline pools in BIGIP\n"

for part in $partitions; do
    echo "Offline pools in Partition: $part"
    pools=$(tmsh list ltm pool /$part/ | awk '/^ltm pool/ {print $3}')

    for pool in $pools; do
        pool_availability=$(tmsh show ltm pool $pool members field-fmt | awk '/status.availability-state/ {print $2}')
        if [[ "$pool_availability" == "offline" ]]; then
            echo -e "Pool $pool:"
            tmsh show ltm pool $pool field-fmt members | awk '
                BEGIN {FS=" "} 
                /node-name/ {mem=$2}
                /addr/ {mbrAddr=$2}
                /port/ {mbrPort=$2}
                /^ {12}status.availability-state/ {avStat=$2}
                /^ {12}status.enabled-state/ {enstate=$2}
                /^ {12}pool-name/ {pname=$2}
                /status.status-reason/ {reason=$2; getline; time=$2 " " $3 " " $4}
                /^{8}/ {print mem, mbrAddr, mbrPort, avStat, enstate, reason, time}'
        fi
    done

    echo -e
done

echo -e "Done!"